-- MySQL Script generated by MySQL Workbench
-- Sat Sep 21 12:42:54 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mydb` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`evento`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`evento` ;

CREATE TABLE IF NOT EXISTS `mydb`.`evento` (
  `evento_id` INT NULL AUTO_INCREMENT,
  `nome` VARCHAR(255) NULL,
  `data_inicio` DATE NULL,
  `data_termino` DATE NULL,
  `descricao` TEXT NULL,
  `data_prorrogacao` DATE NULL,
  `evento_inicio` DATE NULL,
  `evento_termino` DATE NULL,
  `inativo` INT NULL,
  PRIMARY KEY (`evento_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`atividade`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`atividade` ;

CREATE TABLE IF NOT EXISTS `mydb`.`atividade` (
  `atividade_id` INT NOT NULL AUTO_INCREMENT,
  `evento_id` INT NOT NULL,
  `titulo` VARCHAR(255) NULL,
  `responsavel` VARCHAR(255) NULL,
  `carga_horaria` INT(3) NULL,
  `datahora_inicio` DATETIME NULL,
  `datahora_termino` DATETIME NULL,
  `local` VARCHAR(255) NULL,
  `quantidade_vaga` INT(4) NULL,
  `tipo` VARCHAR(255) NULL,
  `inativo` INT NULL,
  PRIMARY KEY (`atividade_id`),
  INDEX `fk_atividade_evento_idx` (`evento_id` ASC) VISIBLE,
  CONSTRAINT `fk_atividade_evento`
    FOREIGN KEY (`evento_id`)
    REFERENCES `mydb`.`evento` (`evento_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`usuario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`usuario` ;

CREATE TABLE IF NOT EXISTS `mydb`.`usuario` (
  `usuario_id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(255) NOT NULL,
  `cpf` VARCHAR(14) NOT NULL,
  `senha` VARCHAR(100) NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  `data_nascimento` DATE NOT NULL,
  `telefone` VARCHAR(20) NOT NULL,
  `endereco` VARCHAR(255) NOT NULL,
  `bairro` VARCHAR(100) NOT NULL,
  `estado` VARCHAR(2) NOT NULL,
  `cidade` VARCHAR(100) NOT NULL,
  `cep` VARCHAR(10) NOT NULL,
  `nacionalidade` VARCHAR(50) NOT NULL,
  `ocupacao` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`usuario_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`presenca`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`presenca` ;

CREATE TABLE IF NOT EXISTS `mydb`.`presenca` (
  `presenca` INT NOT NULL,
  `usuario_id` INT NOT NULL,
  `atividade_id` INT NOT NULL,
  PRIMARY KEY (`presenca`),
  INDEX `fk_presenca_usuario1_idx` (`usuario_id` ASC) VISIBLE,
  INDEX `fk_presenca_atividade1_idx` (`atividade_id` ASC) VISIBLE,
  CONSTRAINT `fk_presenca_usuario1`
    FOREIGN KEY (`usuario_id`)
    REFERENCES `mydb`.`usuario` (`usuario_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_presenca_atividade1`
    FOREIGN KEY (`atividade_id`)
    REFERENCES `mydb`.`atividade` (`atividade_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`tematica`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`tematica` ;

CREATE TABLE IF NOT EXISTS `mydb`.`tematica` (
  `tematica_id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(100) NULL,
  PRIMARY KEY (`tematica_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`trabalho`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`trabalho` ;

CREATE TABLE IF NOT EXISTS `mydb`.`trabalho` (
  `trabalho_id` INT NOT NULL,
  `evento_id` INT NOT NULL,
  `titulo` VARCHAR(200) NULL,
  `arquivo` VARCHAR(100) NULL,
  `status` VARCHAR(100) NULL,
  `id_tematica` INT NOT NULL,
  `apresentador` INT NOT NULL,
  `autor` INT NOT NULL,
  PRIMARY KEY (`trabalho_id`),
  INDEX `fk_submissao_evento1_idx` (`evento_id` ASC) VISIBLE,
  INDEX `fk_trabalho_tematica1_idx` (`id_tematica` ASC) VISIBLE,
  INDEX `fk_trabalho_usuario1_idx` (`apresentador` ASC) VISIBLE,
  INDEX `fk_trabalho_usuario2_idx` (`autor` ASC) VISIBLE,
  CONSTRAINT `fk_submissao_evento1`
    FOREIGN KEY (`evento_id`)
    REFERENCES `mydb`.`evento` (`evento_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_trabalho_tematica1`
    FOREIGN KEY (`id_tematica`)
    REFERENCES `mydb`.`tematica` (`tematica_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_trabalho_usuario1`
    FOREIGN KEY (`apresentador`)
    REFERENCES `mydb`.`usuario` (`usuario_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_trabalho_usuario2`
    FOREIGN KEY (`autor`)
    REFERENCES `mydb`.`usuario` (`usuario_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`permissao`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`permissao` ;

CREATE TABLE IF NOT EXISTS `mydb`.`permissao` (
  `evento_id` INT NOT NULL,
  `usuario_id` INT NOT NULL,
  `permissao` INT NOT NULL DEFAULT 0,
  INDEX `fk_evento_has_usuario_usuario1_idx` (`usuario_id` ASC) VISIBLE,
  INDEX `fk_evento_has_usuario_evento1_idx` (`evento_id` ASC) VISIBLE,
  PRIMARY KEY (`evento_id`, `usuario_id`),
  CONSTRAINT `fk_evento_has_usuario_evento1`
    FOREIGN KEY (`evento_id`)
    REFERENCES `mydb`.`evento` (`evento_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_evento_has_usuario_usuario1`
    FOREIGN KEY (`usuario_id`)
    REFERENCES `mydb`.`usuario` (`usuario_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`usuario_has_Trabalho`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`usuario_has_Trabalho` ;

CREATE TABLE IF NOT EXISTS `mydb`.`usuario_has_Trabalho` (
  `usuario_id` INT NOT NULL,
  `trabalho_id` INT NOT NULL,
  INDEX `fk_usuario_has_Trabalho_Trabalho1_idx` (`trabalho_id` ASC) VISIBLE,
  INDEX `fk_usuario_has_Trabalho_usuario1_idx` (`usuario_id` ASC) VISIBLE,
  PRIMARY KEY (`usuario_id`, `trabalho_id`),
  CONSTRAINT `fk_usuario_has_Trabalho_usuario1`
    FOREIGN KEY (`usuario_id`)
    REFERENCES `mydb`.`usuario` (`usuario_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_usuario_has_Trabalho_Trabalho1`
    FOREIGN KEY (`trabalho_id`)
    REFERENCES `mydb`.`trabalho` (`trabalho_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`avaliador`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`avaliador` ;

CREATE TABLE IF NOT EXISTS `mydb`.`avaliador` (
  `avaliador_id` INT NOT NULL,
  `usuario_id` INT NOT NULL,
  `areaAtuacao` VARCHAR(100) NULL,
  PRIMARY KEY (`avaliador_id`),
  INDEX `fk_avaliador_usuario1_idx` (`usuario_id` ASC) VISIBLE,
  CONSTRAINT `fk_avaliador_usuario1`
    FOREIGN KEY (`usuario_id`)
    REFERENCES `mydb`.`usuario` (`usuario_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`avaliacao`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`avaliacao` ;

CREATE TABLE IF NOT EXISTS `mydb`.`avaliacao` (
  `trabalho_id` INT NOT NULL,
  `avaliador_id` INT NOT NULL,
  `correcao` VARCHAR(100) NULL,
  `parecer` VARCHAR(100) NULL,
  PRIMARY KEY (`trabalho_id`, `avaliador_id`),
  INDEX `fk_trabalho_has_avaliador_avaliador1_idx` (`avaliador_id` ASC) VISIBLE,
  INDEX `fk_trabalho_has_avaliador_trabalho1_idx` (`trabalho_id` ASC) VISIBLE,
  CONSTRAINT `fk_trabalho_has_avaliador_trabalho1`
    FOREIGN KEY (`trabalho_id`)
    REFERENCES `mydb`.`trabalho` (`trabalho_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_trabalho_has_avaliador_avaliador1`
    FOREIGN KEY (`avaliador_id`)
    REFERENCES `mydb`.`avaliador` (`avaliador_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`evento_has_tematica`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`evento_has_tematica` ;

CREATE TABLE IF NOT EXISTS `mydb`.`evento_has_tematica` (
  `evento_id` INT NOT NULL,
  `id_tematica` INT NOT NULL,
  PRIMARY KEY (`evento_id`, `id_tematica`),
  INDEX `fk_evento_has_tematica_tematica1_idx` (`id_tematica` ASC) VISIBLE,
  INDEX `fk_evento_has_tematica_evento1_idx` (`evento_id` ASC) VISIBLE,
  CONSTRAINT `fk_evento_has_tematica_evento1`
    FOREIGN KEY (`evento_id`)
    REFERENCES `mydb`.`evento` (`evento_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_evento_has_tematica_tematica1`
    FOREIGN KEY (`id_tematica`)
    REFERENCES `mydb`.`tematica` (`tematica_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`tipo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`tipo` ;

CREATE TABLE IF NOT EXISTS `mydb`.`tipo` (
  `tipo_id` INT NOT NULL,
  `tipoTrabalho` VARCHAR(45) NULL,
  PRIMARY KEY (`tipo_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`trabalho_has_tipo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`trabalho_has_tipo` ;

CREATE TABLE IF NOT EXISTS `mydb`.`trabalho_has_tipo` (
  `trabalho_id` INT NOT NULL,
  `tipo_id` INT NOT NULL,
  PRIMARY KEY (`trabalho_id`, `tipo_id`),
  INDEX `fk_trabalho_has_tipo_tipo1_idx` (`tipo_id` ASC) VISIBLE,
  INDEX `fk_trabalho_has_tipo_trabalho1_idx` (`trabalho_id` ASC) VISIBLE,
  CONSTRAINT `fk_trabalho_has_tipo_trabalho1`
    FOREIGN KEY (`trabalho_id`)
    REFERENCES `mydb`.`trabalho` (`trabalho_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_trabalho_has_tipo_tipo1`
    FOREIGN KEY (`tipo_id`)
    REFERENCES `mydb`.`tipo` (`tipo_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
